version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 300 chef_gpt.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=chef_gpt.settings_prod
    restart: always

volumes:
  static_volume:
  media_volume: 