# Generated by Django 5.0.2 on 2025-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0002_alter_message_role_savedrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrecipe",
            name="cuisine_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="prep_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="servings",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
