# Generated by Django 5.0.2 on 2025-05-04 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0003_savedrecipe_cuisine_type_savedrecipe_difficulty_and_more"),
    ]

    operations = []
