# Generated by Django 5.0.2 on 2025-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0004_auto_20250504_1930"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_summary_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="message_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="recipe_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_summarized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("recipe_creation", "Recipe Creation"),
                    ("recipe_modification", "Recipe Modification"),
                    ("cooking_question", "Cooking Question"),
                    ("general_question", "General Question"),
                    ("system", "System Message"),
                ],
                default="general_question",
                max_length=20,
            ),
        ),
    ]
