# Generated by Django 5.0.2 on 2025-05-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0005_chatsession_last_summary_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrecipe",
            name="embedding_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
