# Generated by Django 5.0.2 on 2025-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cooking", "0007_userembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="userembedding",
            name="recommendations",
            field=models.JSONField(default=list),
        ),
    ]
