# Message and content length limits
MAX_MESSAGE_LENGTH = 1000
MAX_CHAT_SESSIONS = 50
MAX_RECIPES_PER_USER = 100
MAX_RECIPES_PER_CHAT = 10

# Recipe field length limits
MAX_RECIPE_TITLE_LENGTH = 200
MAX_RECIPE_CONTENT_LENGTH = 10000
MAX_RECIPE_DIFFICULTY_LENGTH = 50
MAX_RECIPE_CUISINE_LENGTH = 100
MAX_RECIPE_PREP_TIME_LENGTH = 50
MAX_RECIPE_SERVINGS_LENGTH = 50
MAX_RECIPE_EMBEDDING_ID_LENGTH = 100 